### PR TITLE
Bump to v5.1.1

### PR DESCRIPTION
**Pull request by karenzone**
Bumps version to publish and pick up changes in #56

### CODE REVIEW

**Comment by karenzone** [comment]
@andsel It looks like we didn't publish at 5.1.0.  Is there any reason we shouldn't publish after this PR is approved?

**Comment by andsel** [comment]
I didn't publish because I thought that all the work on ECS should land in one release, instead of have 2 close. So If you want we could bring also the PR #56 in the `5.1.0`. WDYT?

**Comment by karenzone** [comment]
I'd be totally on board if it were my PR. I'm more hesitant to bundle it with everything else because it's from a contributor, and I don't want it to get lost amidst all the ECS work.  

We shouldn't skip publishing at a minor (5.1.0), so perhaps bundling is our best option.  

If you ever want to put up a PR but hold off publishing, we have the provision to use `## Next` in the changelog description.

**Comment by karenzone** [comment]
@andsel  Nice solution!  I'll follow up with the merge/publish for this one after your done publishing.

**Review by andsel — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
Published at v5.1.1: https://rubygems.org/gems/logstash-integration-jdbc/versions/5.1.1

**Pull request merged**
